shop/main/urls.py
from django.contrib import admin
from django.urls import path
from main import views


urlpatterns = [
    path('', views.home, name='home'),
]

shop/products/urls.py
from django.contrib import admin
from django.urls import path
from products import views

urlpatterns = [
    path('<slug:product_slug>/', views.product_view, name='product'),
    path('categories/<slug:category_slug>/', views.category_view, name='category_view'),
    path('categories/<slug:category_slug>/<slug:subcategory_slug>/', views.category_view, name='subcategory_view'),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('product/', include('products.urls')),
    path('basket/', include('baskets.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main/models.py
from django.db import models

# Create your models here.

shop/products/models.py
from django.db import models
from autoslug import AutoSlugField
from django.utils.text import slugify
from transliterate import translit
# Create your models here.

def custom_slugify(value):
    slug = slugify(value, allow_unicode=True)
    slug = translit(slug, 'ru', reversed=True)
    return slug


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = AutoSlugField(max_length=200, unique=True, populate_from='name', slugify=custom_slugify)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='category_images/', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class CategorySub(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = AutoSlugField(max_length=200, unique=True, populate_from='name', slugify=custom_slugify)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='category_sub_images/', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = AutoSlugField(max_length=200, unique=True, populate_from='name', slugify=custom_slugify)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='product_images/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(CategorySub, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Size(models.Model):
    name = models.CharField(max_length=5)  # For 'XS', 'S', 'M', 'L', 'XL', '30', '31', '32' etc.

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Размер'
        verbose_name_plural = 'Размеры'

class ProductSize(models.Model):
    product = models.ForeignKey(Product, related_name='sizes', on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.product.name[:10]} - {self.size.name}"

    class Meta:
        verbose_name = 'Размер товара'
        verbose_name_plural = 'Размеры товаров'
        ordering = ['size__id']
    

shop/main/views.py
from baskets.models import Basket, BasketItem
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import get_object_or_404, render
from products.models import Category, CategorySub, Product, ProductSize, Size


def home(request: WSGIRequest):
    user = request.user

    # product = Product.objects.get(name='Платье1')
    # size = Size.objects.get(name='M')
    # product_size = ProductSize.objects.get(product=product, size=size)

    # basket, created = Basket.objects.get_or_create(user=user)
    # basket_item, created = BasketItem.objects.get_or_create(basket=basket, product_size=product_size, defaults={'quantity': 0})
    # basket_item.quantity += 1
    # basket_item.save()

    # basket_items = BasketItem.objects.filter(basket=basket)

    products = Product.objects.all()
    products_sizes = {product.id: ProductSize.objects.filter(product=product) for product in products}
    context = {
        'title': 'Главная страница',
        # 'basket': basket_items,
        'categories': Category.objects.all(),
        'products': products,
        'products_sizes': products_sizes,
    }

    return render(request, 'main\home.html', context=context)

shop/products/views.py
from baskets.models import Basket, BasketItem
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import get_object_or_404, render
from products.models import Category, CategorySub, Product, ProductSize, Size


def category_view(request: WSGIRequest, category_slug, subcategory_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    subcategory = None
    
    if subcategory_slug:
        subcategory = get_object_or_404(CategorySub, slug=subcategory_slug, category=category)
        products = Product.objects.filter(subcategory=subcategory)
    else:
        products = Product.objects.filter(category=category)
    
    # Получение доступных размеров для каждого товара
    products_sizes = {product.id: ProductSize.objects.filter(product=product) for product in products}

    context = {
        'title': category.name,
        'categories': Category.objects.all(),
        'category': category,
        'subcategory': subcategory,
        'products': products,
        'products_sizes': products_sizes, 
    }
    for product in products:
        pass

    return render(request, 'main/home.html', context=context)



def product_view(request: WSGIRequest, product_slug:str):

    product = Product.objects.get(slug=product_slug)
    product_sizes = ProductSize.objects.filter(product=product)

    context = {
        'title': product.name,
        'categories': Category.objects.all(),
        'product': product,
        'product_sizes': product_sizes,
    }

    return render(request, 'products\product.html', context=context)

shop/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/svg+xml" href="{% static 'svg\shop.svg' %}">
    <title>{{ title }}</title>
</head>
<body>


{% block header %}

    <ul class="main_nav">
        <li><a href="{% url 'home' %}">Главная</a></li>
        {% for category in categories %}
            <li><a href="{% url 'category_view' category.slug %}">{{ category.name }}</a>
                {% if category.categorysub_set.all %}
                    <ul>
                        {% for subcategory in category.categorysub_set.all %}
                            <li><a href="{% url 'subcategory_view' category.slug subcategory.slug %}">{{ subcategory.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock header %}

<main>
    {% block main %}{% endblock main %}
</main>
    
</body>
</html>

shop/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load custom_filters %}






{% block main %}
    <section class="products">
        {% for product in products %}
            <article class="product">
                <a href="{% url 'product' product.slug %}">
                    <div class="img">
                        {% if product.image %}  
                            <img src="{{ product.image.url }}" alt="">
                        {% endif %}
                    </div>
                    <div class="title">{{ product.name }}</div>
                    <ul class="size">
                        {% if products_sizes|get_data_by_id:product %}
                            
                            {% for product_size in products_sizes|get_data_by_id:product %}
                                <li>{{ product_size.size.name }}</li>
                            {% endfor %}

                        {% else %}
                            <li>Нет размеров</li>
                        {% endif %}
                    </ul>
                    <div class="price">{{ product.price }}</div>
                </a>
            </article>
        {% endfor %}
    </section>
{% endblock main %}

    
    

    



    {% if basket %}
        <p>Корзина:</p>
        <ul>
            {% for basket_item in basket %}
                <li>{{ basket_item }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    
    

shop/main/templates/main/product.html
{% extends 'main/base.html' %}
{% load static %}
{% load custom_filters %}

{% block header %}
{% endblock header %}

{% block main %}
    <section class="product">
        <div class="row">
            <div class="img">
                <img src="{{ product.image.url }}" alt="">
            </div>

            <div class="data">
                <ul class="breads">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'category_view' product.category.slug %}">{{ product.category }}</a></li>
                    
                    {% if product.subcategory %}
                        <li><a href="{% url 'subcategory_view' product.category.slug product.subcategory.slug %}">{{ product.subcategory }}</a></li>
                    {% endif %}  
                </ul>

                <div class="title">{{ product.name }}</div>
                <div class="price">{{ product.price }} UAH</div>

                <ul class="size">
                    {% if product_sizes %}
                        {% for ps in product_sizes %}
                            <li data-href="{% url 'basket_update' 'get' product.id %}">{{ ps.size.name }}</li>
                        {% endfor %}
                    {% else %}
                        <p>Нет размеров</p>
                    {% endif %}
                </ul>
                {% include 'products\inc\basket-btns.html' %}
                <script src="{% static 'js/main.js' %}"></script>
                <script src="{% static 'js/basket_update.js' %}"></script>

            </div>
        </div>
        {% if product.description %}
            <div class="description">
                <div class="description-title">ОПИСАНИЕ</div>
                <div class="text">{{ product.description|linebreaksbr }}</div>
            </div> 
        {% endif %}
        
    </section>
    
{% endblock main %}